### ISSUE TITLE
Allow the user to customize the callback URL

### ISSUE THREAD

**Issue by jentz** [jentz/vigilant-dollop#26]
The user should be able to add a --callback-url to the authorization_code command and the tool should respect the port and path of the callback URL.

For example, if the callback url is `http://localhost:7777/cb` then the tool will start the http server on port 7777 and map the auth code callback handler to `/cb`.

**Comment by remcojansen** [comment]
An alternative might be to let the http server listen automatically on the URL provided as the redirect URI, without adding an additional argument?

**Comment by jentz** [comment]
Many authorization servers will not allow non-TLS enabled redirects unless they are localhost. The use case I had in mind was to allow for a developer that sets up a TLS terminating proxy like Ngrok or similar which would then forward HTTP to localhost on the developers laptop.

For this reason, I think that while one can imagine allowing and respecting the direct configuration of the callback listener, it is still very useful to allow the CLI to issue a redirect URI of the user's choosing and assume they have setup the correct ingress/proxy to forward it to the CLI listener.

**Comment by remcojansen** [comment]
Right, that scenario makes sense to me. To support this, I think we should introduce an additional command-line argument for providing the `redirect-uri` that is separate from the `callback-uri`. Perhaps the `callback-uri` can default to the `redirect-uri` or vice versa, depending on what we deem most logical?
